version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer
      POSTGRES_PASSWORD: example
    volumes:
      - ./init/postgress/dump:/tmp/dump
      - ./init/postgress/script:/docker-entrypoint-initdb.d