DROP TABLE IF EXISTS PURCHASE_TRANSACTION;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS COUNTRY;


CREATE TABLE COUNTRY (
ID VARCHAR(36) PRIMARY KEY,
NAME VARCHAR(200) NOT NULL
);

CREATE TABLE CUSTOMER (
ID VARCHAR(36) PRIMARY KEY,
FULL_NAME VARCHAR(200) NOT NULL,
PHONE_NUMBER VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(200) NOT NULL,
CREATED_AT DATE NOT NULL,
COUNTRY_ID VARCHAR(36),
FOREIGN KEY (COUNTRY_ID)  REFERENCES COUNTRY (ID)
);

CREATE TABLE PURCHASE_TRANSACTION (
ID VARCHAR(36) PRIMARY KEY,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(19,4),
CUSTOMER_ID VARCHAR(36),
CREATED_AT DATE NOT NULL,
FOREIGN KEY (CUSTOMER_ID)  REFERENCES CUSTOMER (ID)
);

